spring:
  application:
    name: ms-users
  cloud:
    vault:
      host: ${VAULT_ADDR:localhost}
      port: ${VAULT_PORT:8200}
      token: ${VAULT_TOKEN:root}
      scheme: ${VAULT_SCHEME:http}
      kv:
        enabled: true
  config:
    import: vault://
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:""}

server:
  port: 8080
logging:
  level:
    root: info
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,refresh
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
